version: '3'
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - '5001:5001'

  db:
    image: mysql:latest
    ports:
      - '32000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db:/docker-entrypoint-initdb.d/:ro
