openapi: 3.0.0
tags:
  - User
description: A new user signs up and the user information is recorded in the database.
consumes:
  - application/json
parameters:
  - in: body
    name: user
    description: The user sign up information.
    schema:
      type: object
      required:
        - email
        - name
        - username
        - password
      properties:
        email:
          type: string
          example: 123@gmail.com
        name:
          type: string
          example: UC Cheng
        username:
          type: string
          example: UCC
        password:
          type: string
          example: 12345678
responses:
  200:
    description: The user signs up successfully.
    schema:
      type: object
      required:
        - data
        - msg
      properties:
        data:
          type: object
          example: {}
        msg:
          type: string
          example: 'Sign up successfully!'
  400:
    description: The input data(email/ name/ username/ password) is invalid or the email is already exist.
    schema:
      type: object
      required:
        - data
        - msg
      properties:
        data:
          type: object
          example: {}
        msg:
          type: string
          example: 'Error: the length of password is over 20 or less 8.'
  500:
    description: Server error
    schema:
      type: object
      required:
        - data
        - msg
      properties:
        data:
          type: object
          example: {}
        msg:
          type: string
          example: 'The system gets error. Please contact with system administrator.'
