openapi: 3.0.0
tags:
  - User
description: Get the user information in the database.
security:
  - Bearer: ['Authorization']
responses:
  '200':
    description: Get user information successfully.
    schema:
      type: object
      required:
        - data
        - msg
      properties:
        data:
          type: object
          example:
            {
              'email': '1@gmail.com',
              'name': 'abc',
              'uid': 6,
              'username': 'abc',
            }
        msg:
          type: string
          example: 'Get user information successfully.'
  '401':
    description: The format of access_token is wrong or expired.
    schema:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
          example: 'The token has expire.'
  '422':
    description: The authentication of access_token is failed.
    schema:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
          example: 'Signature verification failed'
  '500':
    description: Server error.
    schema:
      type: object
      required:
        - data
        - msg
      properties:
        data:
          type: object
          example: {}
        msg:
          type: string
          example: 'The system is error. please contact with system administrator.'
